-- Your SQL goes here
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR NOT NULL UNIQUE,
  email VARCHAR NOT NULL UNIQUE,
  pass_hash VARCHAR NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
)